name: goreleaser

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  goreleaser_x64:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ">=1.24.1"

      # Install static libraries for static linking on ubuntu image:
      # '-linkmode external -extldflags "-static -lpcsclite"'
      - name: Download required libraries
        run: |
          sudo apt-get update
          DEBIAN_FRONTEND=noninteractive sudo apt-get install pkg-config cmake libpolkit-gobject-1-dev flex libudev-dev meson git -y

      - name: Build lib pcsclite static
        run: |
          cd /tmp
          git clone https://github.com/LudovicRousseau/PCSC.git
          cd PCSC
          meson setup builddir -Dlibsystemd=false -Ddefault_library=both
          cd builddir
          meson compile
          sudo meson install

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release -f .github/goreleaser/goreleaser-x64.yaml --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  goreleaser_arm:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ">=1.24.1"

      # Install static libraries for static linking on ubuntu image:
      # '-linkmode external -extldflags "-static -lpcsclite"'
      - name: Download required libraries
        run: |
          sudo apt-get update
          DEBIAN_FRONTEND=noninteractive sudo apt-get install pkg-config cmake libpolkit-gobject-1-dev flex libudev-dev meson git -y

      - name: Build static lib pcsclite
        run: |
          cd /tmp
          git clone https://github.com/LudovicRousseau/PCSC.git
          cd PCSC
          meson setup builddir -Dlibsystemd=false -Ddefault_library=both
          cd builddir
          meson compile
          sudo meson install

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release -f .github/goreleaser/goreleaser-arm.yaml --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
